---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(meta.arrR)

```

```{r}

# get starting values
starting_values <- meta.arrR::default_starting_values

starting_values$pop_n <- c(1, 1, 8)

# get parameters
parameters <- meta.arrR::default_parameters

# create 5 reef cells in center of seafloor
reef_matrix <- matrix(data = c(-1, 0, 0, 1, 1, 0, 0, -1, 0, 0), 
                      ncol = 2, byrow = TRUE)

# setup extent and grain
extent <- c(50, 50)

grain <- 1

# set time per iterations
min_per_i <- 120

# run the model for n years
years <- 1
max_i <- (60 * 24 * 365 * years) / min_per_i

# save results only every m days
days <- 5
save_each <- 1 # (24 / (min_per_i / 60)) * days

max_i %% save_each

parameters$pop_mean_stationary <- max_i / 100

parameters$pop_var_stationary <- 0 # parameters$pop_mean_stationary * 1

metasyst <- setup_meta(n = 3, extent = extent, grain = grain, reefs = reef_matrix, 
                       starting_values = starting_values, parameters = parameters)

# nutr_input <- simulate_input_sine(n = 3, timestep = 1:max_i,
#                                   period_mn = 0.005, period_sd = 0, 
#                                   amplitude_mn = 0.001, amplitude_sd = 0)
# 
# plot_nutrient_input(nutr_input)

```

```{r run}

result <- simulate_meta(metasyst = metasyst, nutr_input = NULL,
                        parameters = parameters, reef_attraction = TRUE,
                        max_i = max_i, save_each = save_each, min_per_i = min_per_i, 
                        verbose = TRUE)

```

```{r stuff}

# plot(result, what = "seafloor")

# plot_local_abund(result)

# get_abundance(result)

# dplyr::bind_rows(result$fishpop) %>% 
#   dplyr::filter(timestep != 0) %>% 
#   dplyr::mutate(stat_class = dplyr::case_when(stationary == 0 ~ "moved", 
#                                               TRUE ~ "stayed")) %>%
#   dplyr::group_by(id, stat_class) %>% 
#   dplyr::summarise(n = dplyr::n()) %>% 
#   dplyr::filter(!is.na(id)) %>% 
#   dplyr::left_join(data.frame(result$fishpop_stationary), by = "id") %>% 
#   dplyr::arrange(-n)

# library(ggplot2)
# library(patchwork)
# library(dplyr)
# 
# ii <- 3
# 
# gg_ag <- result$seafloor[[ii]] %>% 
#   dplyr::filter(timestep == max(timestep)) %>% 
#   ggplot() + 
#   geom_raster(aes(x = x, y = y, fill = ag_biomass)) + 
#   coord_equal() + 
#   scale_fill_viridis_c() + 
#   theme_classic()
# 
# gg_bg <- result$seafloor[[ii]] %>% 
#   dplyr::filter(timestep == max(timestep)) %>% 
#   ggplot() + 
#   geom_raster(aes(x = x, y = y, fill = bg_biomass)) + 
#   coord_equal() + 
#   scale_fill_viridis_c() + 
#   theme_classic()
# 
# gg_ag + gg_bg

```
