# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_list_to_matrix
#'
#' @description Rcpp list to matrix
#'
#' @param x List
#'
#' @details
#' Convert a list to a list
#'
#' @return matrix
#'
#' @aliases rcpp_list_to_matrix
#' @rdname rcpp_list_to_matrix
#'
#' @keywords export
rcpp_list_to_matrix <- function(x, n, pop_n) {
    .Call(`_meta_arrR_rcpp_list_to_matrix`, x, n, pop_n)
}

#' rcpp_matrix_to_list
#'
#' @description Rcpp list to matrix
#'
#' @param x List
#'
#' @details
#' Convert a list to a list
#'
#' @return matrix
#'
#' @aliases rcpp_matrix_to_list
#' @rdname rcpp_matrix_to_list
#'
#' @keywords export
rcpp_matrix_to_list <- function(x, n) {
    .Call(`_meta_arrR_rcpp_matrix_to_list`, x, n)
}

#' rcpp_move_meta
#'
#' @description Rcpp list to matrix
#'
#' @param x List
#'
#' @details
#' Convert a list to a list
#'
#' @return matrix
#'
#' @aliases rcpp_move_meta
#' @rdname rcpp_move_meta
#'
#' @keywords export
rcpp_move_meta <- function(fishpop_values, n, pop_n, prob_move) {
    invisible(.Call(`_meta_arrR_rcpp_move_meta`, fishpop_values, n, pop_n, prob_move))
}

