# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_find
#'
#' @description
#' Rcpp find.
#'
#' @param x Integer with with value to find.
#' @param y NumericVector with values to find all elements of x in.
#'
#' @details
#' Returns the index of the \code{x} object within the \code{y} object.
#' The index of the first element is 0. If an element is not present within \code{y} object,
#' \code{NA} is returned. Returns only the first index of an object if present multiple
#' times in the \code{y} object.
#'
#' @return NumericVector
#'
#' @aliases rcpp_find
#' @rdname rcpp_find
#'
#' @export
rcpp_find <- function(x, y) {
    .Call(`_meta_arrR_rcpp_find`, x, y)
}

#' rcpp_get_table
#'
#' @description
#' Rcpp get table.
#'
#' @param x Vector with values.
#' @param n Integer with maximum number of classes.
#'
#' @details
#' Returns table with value count. Only values x > 0 are allowed.
#'
#' @return vector
#'
#' @aliases rcpp_get_table
#' @rdname rcpp_get_table
#'
#' @export
rcpp_get_table <- function(x, n) {
    .Call(`_meta_arrR_rcpp_get_table`, x, n)
}

#' rcpp_list_to_matrix
#'
#' @description
#' Rcpp list to matrix.
#'
#' @param fishpop List with individuals within local metaecosystems.
#' @param pop_n_sum Integer with number of individuals.
#' @param id If TRUE, column with metaecosystem id is added.
#'
#' @details
#' Converts list with individuals within a local metaecosystem to one matrix. If
#' \code{id = TRUE} a column identifying the metaecosystem is added.
#'
#' @return matrix
#'
#' @aliases rcpp_list_to_matrix
#' @rdname rcpp_list_to_matrix
#'
#' @export
rcpp_list_to_matrix <- function(fishpop, pop_n_sum, id) {
    .Call(`_meta_arrR_rcpp_list_to_matrix`, fishpop, pop_n_sum, id)
}

#' rcpp_matrix_to_list
#'
#' @description
#' Rcpp matrix to list.
#'
#' @param fishpop Matrix with fish population.
#' @param n Integer with number of total metaecosystems.
#'
#' @details
#' Converts individual matrix to a list split by metaecosystems.
#'
#' @return list
#'
#' @aliases rcpp_matrix_to_list
#' @rdname rcpp_matrix_to_list
#'
#' @export
rcpp_matrix_to_list <- function(fishpop, n) {
    .Call(`_meta_arrR_rcpp_matrix_to_list`, fishpop, n)
}

#' rcpp_move_meta
#'
#' @description
#' Rcpp move meta.
#'
#' @param fishpop List with fish population.
#' @param seafloor_probs Matrix with local ecosystems probabilities.
#' @param fishpop_attributes Matrix with residence and reserves_thres values for each individual.
#' @param extent Spatial extent of the seafloor raster.
#'
#' @details
#' Simulate movement across local metaecosystem. Individuals move to a new local
#' metaecosystem with a certain probability each timestep. The probability increases
#' depending on the residence value and how long individuals already stayed on local
#' metaecosystem. To avoid this movement set \code{parameters$move_residence <= 0}.
#'
#' @return list
#'
#' @aliases rcpp_move_meta
#' @rdname rcpp_move_meta
#'
#' @export
rcpp_move_meta <- function(fishpop, seafloor_probs, fishpop_attributes, extent) {
    .Call(`_meta_arrR_rcpp_move_meta`, fishpop, seafloor_probs, fishpop_attributes, extent)
}

#' rcpp_simulate_meta
#'
#' @description
#' Rcpp run simulation of metaecosystems processes.
#'
#' @param seafloor,fishpop List with seafloor and fishpop data of metaecosystems.
#' @param nutrients_input List with amount of nutrient input each timestep.
#' @param fishpop_attributes Matrix with residence and reserves_thres values for each individual
#' @param seafloor_probs Matrix with local ecosystems probabilities.
#' @param seafloor_track,fishpop_track List with entry for each saving timestep and metaecosystems.
#' @param parameters List with parameters.
#' @param movement String specifying movement algorithm. Either 'rand', 'attr' or 'behav'.
#' @param extent Vector with extent (xmin,xmax,ymin,ymax).
#' @param dimensions Vector with dimensions (nrow, ncol).
#' @param max_i Integer with maximum number of simulation timesteps.
#' @param min_per_i Integer to specify minutes per i.
#' @param save_each Numeric how often data should be saved to return.
#' @param seagrass_each Integer how often (each i * x) seagrass dynamics will be simulated.
#' @param burn_in Numeric with timesteps used to burn in.
#' @param verbose If TRUE, progress reports are printed.
#'
#' @details
#' Wrapper function including all sub-processes. The core of the function is a
#' nested loop through all i) time steps and ii) all local metaecosystems.
#'
#' The functions is a 'wrapper' around the following sub-processes: i) movement across
#' local metaecosystems (outter loop) (ii) nutrient input, (iii) seagrass growth,
#' (iv) detritus mineralization, (v) movement of individuals, (vi) respiration of
#' individuals, (vii) growth of individuals, (viii) mortality of individuals,
#' (ix) diffusion of nutrients/detritus, and (x) nutrient output (all inner loop).
#'
#' For a detailed description of all sub-processes (with exception of (i)), see the
#' \pkg{arrR} package.
#'
#' @references
#' For a detailed model description, see Esquivel, K., Hesselbarth, M.H.K., Allgeier, J.E.
#' In preparation. Mechanistic support for increased primary production around artificial reefs.
#'
#' Add references about meta approach.
#'
#' @return void
#'
#' @aliases rcpp_simulate_meta
#' @rdname rcpp_simulate_meta
#'
#' @export
rcpp_simulate_meta <- function(seafloor, fishpop, nutrients_input, fishpop_attributes, seafloor_probs, seafloor_track, fishpop_track, parameters, movement, extent, dimensions, max_i, min_per_i, save_each, seagrass_each, burn_in, verbose) {
    invisible(.Call(`_meta_arrR_rcpp_simulate_meta`, seafloor, fishpop, nutrients_input, fishpop_attributes, seafloor_probs, seafloor_track, fishpop_track, parameters, movement, extent, dimensions, max_i, min_per_i, save_each, seagrass_each, burn_in, verbose))
}

