# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_table
#'
#' @description Rcpp get table
#'
#' @param x Vector with values.
#' @param n Integer with maximum number of classes.
#'
#' @details
#' Returns table with value count
#'
#' @return vector
#'
#' @aliases rcpp_get_table
#' @rdname rcpp_get_table
#'
#' @keywords export
rcpp_get_table <- function(x, n) {
    .Call(`_meta_arrR_rcpp_get_table`, x, n)
}

#' rcpp_list_to_matrix
#'
#' @description Rcpp list to matrix
#'
#' @param x List with individuals within metaecosystems.
#' @param pop_n Integer with number of indiviuals.
#'
#' @details
#' Converts list with individuals within metaecosystems to one matrix. Adds coloumn
#' with metasystem id
#'
#' @return matrix
#'
#' @aliases rcpp_list_to_matrix
#' @rdname rcpp_list_to_matrix
#'
#' @keywords export
rcpp_list_to_matrix <- function(x, pop_n) {
    .Call(`_meta_arrR_rcpp_list_to_matrix`, x, pop_n)
}

#' rcpp_matrix_to_list
#'
#' @description Rcpp matrix to list
#'
#' @param x Matrix with fish population.
#' @param n Integer with number of metaecosystems.
#'
#' @details
#' Converts a matrix with fishpopulation to a list split by metaecosystem.
#'
#' @return list
#'
#' @aliases rcpp_matrix_to_list
#' @rdname rcpp_matrix_to_list
#'
#' @keywords export
rcpp_matrix_to_list <- function(x, n) {
    .Call(`_meta_arrR_rcpp_matrix_to_list`, x, n)
}

#' rcpp_move_meta
#'
#' @description Rcpp list to matrix
#'
#' @param fishpop_values List with fish population.
#' @param pop_n Integer with total number of individuals.
#' @param fishpop_stationary Matrix with stationary value for each individual.
#' @param extent Spatial extent of the seafloor raster.
#'
#' @details
#' Simulate movement across local metaecosystem. Individuals move to a new local
#' metaecosystem with a certain probability each timestep.
#'
#' @return void
#'
#' @aliases rcpp_move_meta
#' @rdname rcpp_move_meta
#'
#' @keywords export
rcpp_move_meta <- function(fishpop_values, pop_n, fishpop_stationary, extent) {
    .Call(`_meta_arrR_rcpp_move_meta`, fishpop_values, pop_n, fishpop_stationary, extent)
}

